### ISSUE TITLE
How to compile on sudoless travis

### ISSUE THREAD

**Issue by wilsonge** [jedisct1/libsodium-php#160]
Hi,
I'm really struggling to get this library to compile in travis' sudoless environment. I took some inspiration from the google project here https://github.com/google/hat-backup/blob/master/travis-install-libsodium.sh and shoved libsodium into the home directory and then used pkg-config 

Implementation is here: https://github.com/joomla/joomla-cms/blob/1deae8237f91f70c3839b514f41c2babfa86f23b/build/travis/unit-tests.sh#L31-L36 You can see the results in this build https://travis-ci.org/joomla/joomla-cms/jobs/309495893

I'm suspect that it's a really simple pebak problem - but hopefully you can advise :)

**Comment by jedisct1** [comment]
PECL needs a way to find the library in a non-standard path. But I don't know how to do that.

**Comment by wilsonge** [comment]
Maybe I'm missing something but that's what pkg-config should be doing right? I mean `config.m4` is finding libsodium according to this line using pkg-config https://travis-ci.org/joomla/joomla-cms/jobs/309495893#L2666

**Comment by jedisct1** [comment]
Maybe it's finding the headers, but it fails at runtime. Maybe you need to add the path to `LD_LIBRARY_PATH`.

**Comment by wilsonge** [comment]
I already am https://github.com/joomla/joomla-cms/blob/4.0-dev/build/travis/unit-tests.sh#L35

**Comment by jedisct1** [comment]
Did you try without PECL? By downloading/extracting the package, then running `phpize`, `./configure --with-sodium` and then `make install`?

**Comment by wilsonge** [comment]
OK Just amended code to that and get the same result. the configure routine fails in exactly the same place

**Comment by wilsonge** [comment]
@jedisct1 don't suppose you have any good ideas here? Is there a working example of a pkg-config install - just to rule out there being some sort of bug with using that to discover the libsodium library. Not that I can see anything obviously wrong with the `config.m4` file :/

**Comment by jedisct1** [comment]
Unfortunately, no, I don't have any ideas :(

**Comment by barkermn01** [comment]
Does PECL not fall onto the PATH variable could you not just append your path to the PATH
`export PATH="$PATH;/libsodium/bin"`?

**Comment by Nenglish7** [comment]
There is a way of adding it.

An example travis configuration file.
```
language: php
sudo: false
php:
    - 7.0.27
    - 7.1.13
    - 7.2.1
    - "nightly"
matrix:
    fast_finish: true
    allow_failures:
        - php: "nightly"
os:
    - windows
    - linux
before_install:
    - git clone -b stable https://github.com/jedisct1/libsodium.git
    - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
install:
    - pecl install libsodium
    - travis_retry composer install --no-interaction
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
```
